<?php

use Illuminate\Database\Seeder;
use App\Course;
class AddUKCourses extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = array(
"Academic studies in education",
"Academic studies in nursery education",
"Academic studies in primary education",
"Academic studies in specialist education",
"Accountancy",
"Accountancy, finance, business & management studies",
"Acoustics & vibration",
"Acting",
"Adult nursing",
"Aerospace engineering",
"African studies",
"Agricultural sciences",
"Agriculture",
"Agriculture, horticulture & veterinary sciences",
"American studies",
"Anatomy, physiology & pathology",
"Ancient history",
"Ancient language studies",
"Animal science",
"Animation",
"Anthropology",
"Archaeology",
"Architecture",
"Architecture, building & planning",
"Art & design",
"Artificial intelligence",
"Asian (other) studies",
"Astronomy",
"Audio technologies",
"Australasian studies",
"Banking",
"Bioengineering, biomedical engineering & clinical engineering",
"Biological sciences",
"Biology",
"Biotechnologies",
"Botany",
"British & Irish history",
"Buddhism",
"Building & construction",
"Business studies",
"Celtic studies",
"Chemical, process & energy engineering",
"Chemistry",
"Chinese studies",
"Choreography",
"Christianity",
"Cinematics & photography",
"Cinematography",
"Civil engineering",
"Classical Greek studies",
"Classical studies",
"Clothing/fashion design",
"Communications engineering",
"Comparative literary studies",
"Complementary medicines, therapies & well-being",
"Composition",
"Computational physics",
"Computer generated visual & audio effects",
"Computer science",
"Computing & information technology",
"Counselling",
"Craft skills",
"Crafts",
"Criminology",
"Dance",
"Dance & culture",
"Dance & drama",
"Dental nursing",
"Dentistry",
"Divinity",
"Drama",
"Earth sciences",
"Ecology",
"Economics",
"Education & teaching",
"Electronic & electrical engineering",
"Engineering",
"Engineering & manufacturing",
"English as a second language",
"English language",
"English language & literature",
"English literature",
"English studies",
"Environmental & marine biology",
"Environmental health",
"Environmental sciences",
"European studies",
"Fabric & leather crafts",
"Farming",
"Film & sound recording",
"Finance",
"Fine art",
"Food & drink",
"Food, leisure & hospitality",
"Forensic & archaeological sciences",
"Forestry & arboriculture",
"French studies",
"Gaelic studies",
"Games",
"Genetics",
"Geography & geology",
"Geology",
"German studies",
"Glass crafts",
"Graphic design",
"Health Information Systems",
"Heritage studies",
"Hinduism",
"History",
"History of art",
"Horticulture",
"Hospitality",
"Human geography",
"Human resource management",
"Illustration",
"Imaginative writing",
"Industrial/product design",
"Information management",
"Information systems",
"Interactive & electronic design",
"Interior design",
"International politics",
"Investment & insurance",
"Irish studies",
"Islam",
"Italian studies",
"Japanese studies",
"Journalism",
"Judaism",
"Landscape & garden design",
"Latin studies",
"Law",
"Law by geographic area",
"Law by topic",
"Learning disability nursing",
"Leisure & tourism studies",
"Linguistics",
"Linguistics & classics",
"Livestock",
"Management studies",
"Marine sciences",
"Maritime geography",
"Maritime technologies",
"Marketing",
"Material technologies",
"Mathematics",
"Mathematics & statistics",
"Mechanical engineering",
"Media & creative arts",
"Media Studies",
"Medical physics",
"Medical technology",
"Medicine",
"Medicine, dentistry & optometry",
"Mental health nursing",
"Metal crafts",
"Microbiology",
"Middle Eastern studies",
"Midwifery",
"Minerals technologies",
"Modern European languages & cultural studies",
"Modern history",
"Molecular biology, biophysics & biochemistry",
"Moving image techniques",
"Music",
"Music education/teaching",
"Music studies",
"Music technology & industry",
"Musical performance",
"Musicology",
"Naval architecture",
"Neuroscience",
"Nursery teaching",
"Nursing",
"Nursing, health & wellbeing",
"Nutrition & Dietetics",
"Occupational health & safety",
"Office skills",
"Operational research",
"Optometry",
"Paramedical science",
"Performance & live arts",
"Pharmacology, toxicology & pharmacy",
"Philosophy",
"Philosophy, theology & religion",
"Photography",
"Physical geography",
"Physical Sciences",
"Physics",
"Physiotherapy",
"Planning (urban, rural & regional)",
"Podiatry",
"Politics",
"Portuguese studies",
"Primary teaching",
"Producing & directing motion pictures",
"Production & manufacturing engineering",
"Psychology",
"Publishing",
"Recreation & leisure studies",
"Reed crafts",
"Research & study skills in education",
"Rural estate management",
"Russian & East European studies",
"Scandinavian studies",
"Scottish studies",
"Secondary teaching",
"Social policy",
"Social studies",
"Social work",
"Sociology",
"Software engineering",
"Spanish studies",
"Specialist teaching",
"Speech & language therapy",
"Sport & exercise science",
"Sport sciences",
"Sports coaching",
"Statistics",
"Surface decoration",
"Systems engineering",
"Teacher training",
"Teaching English as a Foreign Language (TEFL)",
"Technologies",
"Theatre studies",
"Theology",
"Topical history",
"Translation studies",
"Types of dance",
"Types of music",
"Veterinary medicine",
"Visual & audio effects",
"Welsh studies",
"Wood crafts",
"World history",
"World languages & cultural studies",
"Zoology"
);

		foreach($names as $name) {
			Course::create(['name' => $name]);
		}
    }
}
